### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by claycat** [CapstoneDesign2-WHEALTH/whealth_UI#6]
Wiki should be updated
Some image postings (before and after mentor feedback) would be nice.
Brief introductions about the features you added should be posted also.
e.g.)
1. push alarms
2. why water is good for your health banners
3. water consumption graph
4. additional features? (if planned, post new issue)

**Comment by jhy979** [comment]
Wiki 업데이트 완료
1. 피드백 과정에서의 새로운 UI 모습
2. Drink, Alarm, Chart, Profile 컴포넌트 별 사용한 라이브러리 기술
